//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentRoom()
        {
            this.UsedServices = new HashSet<UsedService>();
        }
    
        public int id { get; set; }
        public int roomID { get; set; }
        public string renterName { get; set; }
        public string tel { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedService> UsedServices { get; set; }
        public virtual Room Room { get; set; }
    }
}
