//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTro
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.RentRooms = new HashSet<RentRoom>();
        }

        private int _id;
        private Nullable<int> _idCategory;
        private string _name;
        private int __status;
        public int Id
        {
            get
            {
                return _id;
            }

            set
            {
                _id = value;
            }
        }

        public int? IdCategory
        {
            get
            {
                return _idCategory;
            }

            set
            {
                _idCategory = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged.Invoke(this, new PropertyChangedEventArgs("IdCategory"));
                }
            }
        }

        public string Name
        {
            get
            {
                return _name;
            }

            set
            {
                _name = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged.Invoke(this, new PropertyChangedEventArgs("Name"));
                }
            }
        }

        public int Status
        {
            get
            {
                return __status;
            }

            set
            {
                __status = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged.Invoke(this, new PropertyChangedEventArgs("Status"));
                }
            }
        }
        public string TenLoai(List<RoomCategory> ls)
        {
            foreach (var it in ls)
            {
                if (IdCategory == it.Id)
                    return it.Name;
            }
            return "";
        }
        public void CreateId(List<Room> listroom)
        {
            this.Id = listroom.Count + 1;
        }
        public event PropertyChangedEventHandler PropertyChanged;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentRoom> RentRooms { get; set; }
        public virtual RoomCategory RoomCategory { get; set; }
    }
}
