//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class USDDetail
    {
        public int usID { get; set; }
        public int sID { get; set; }
        public int times { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual UsedService UsedService { get; set; }
    }
}
